#!/bin/bash

source secret

base_url='kimstebel.cloudant.com/uploads/notebooks'
export rev=$(curl -s "https://${creds}@${base_url}" | jq -r '._rev')
rm logs
touch logs
function upload {
  curl -s "https://${creds}@${base_url}/$1" -X PUT --data-binary "@$1" -H "Content-Type: $2" -H "If-Match: $rev" | tee -a logs | jq -r '.rev'
}

export rev=$(upload 'index.html' 'text/html')
export rev=$(upload 'screenshot.png' 'image/png')
export rev=$(upload 'tmpnb.png' 'image/png')

cat logs

echo "https://${base_url}/index.html"

